#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_struct

import gi
gi.require_version('Hinawa', '4.0')
from gi.repository import Hinawa

target_type = Hinawa.CycleTime
methods = (
    'new',
    'get_system_time',
    'get_clock_id',
    'get_fields',
    'get_raw',
    'compute_tstamp',
    'parse_tstamp',
)

if not test_struct(target_type, methods):
    exit(ENXIO)
