#!/usr/bin/env python3

import sys
import errno

from helper import test

import gi
gi.require_version('Hinawa', '1.0')
from gi.repository import Hinawa

target = Hinawa.FwFcp()
props = (
    'timeout',
)
methods = (
    'listen',
    'unlisten',
    'transact',
)
signals = ()

if not test(target, props, methods, signals):
    sys.exit(errno.ENXIO)
