#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test

import gi
gi.require_version('Hinawa', '2.0')
from gi.repository import Hinawa

target = Hinawa.FwNode()
props = (
    'node-id',
    'local-node-id',
    'bus-manager-node-id',
    'ir-manager-node-id',
    'root-node-id',
    'generation',
)
methods = (
    'new',
    'open',
    'get_config_rom',
    'create_source',
)
vmethods = ()
signals = (
    'bus-update',
)

if not test(target, props, methods, vmethods, signals):
    exit(ENXIO)
