#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('Hinawa', '3.0')
from gi.repository import Hinawa

target_type = Hinawa.FwNode
props = (
    'node-id',
    'local-node-id',
    'bus-manager-node-id',
    'ir-manager-node-id',
    'root-node-id',
    'generation',
)
methods = (
    'new',
    'open',
    'get_config_rom',
    'create_source',
)
vmethods = (
    'do_bus_update',
    'do_disconnected',
)
signals = (
    'bus-update',
    'disconnected',
)

if not test_object(target_type, props, methods, vmethods, signals):
    exit(ENXIO)
