#!/usr/bin/env python3

import sys
import errno

from helper import test

import gi
gi.require_version('Hinawa', '2.0')
from gi.repository import Hinawa

target = Hinawa.FwResp()
props = ()
methods = (
    'register',
    'unregister',
    'get_req_frame',
    'set_resp_frame',
)
signals = (
    'requested',
)

if not test(target, props, methods, signals):
    sys.exit(errno.ENXIO)
