#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('Hinawa', '3.0')
from gi.repository import Hinawa

target_type = Hinawa.FwReq
props = (
    'timeout',
)
methods = (
    'new',
    'transaction',
    'transaction_async',
    'transaction_sync',
    'request',
    'transaction_with_tstamp',
)
vmethods = (
    'do_responded',
    'do_responded2',
)
signals = (
    'responded',
    'responded2',
)

if not test_object(target_type, props, methods, vmethods, signals):
    exit(ENXIO)
