#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test

import gi
gi.require_version('Hinawa', '3.0')
from gi.repository import Hinawa

target = Hinawa.FwResp()
props = (
    'is-reserved',
    'offset',
    'width',
)
methods = (
    'new',
    'get_req_frame',
    'set_resp_frame',
    'reserve',
    'release',
)
vmethods = (
    'do_requested',
    'do_requested2',
)
signals = (
    'requested',
    'requested2',
)

if not test(target, props, methods, vmethods, signals):
    exit(ENXIO)
