#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test

import gi
gi.require_version('Hinawa', '2.0')
from gi.repository import Hinawa

target = Hinawa.FwUnit()
props = (
    'node-id',
    'local-node-id',
    'bus-manager-node-id',
    'ir-manager-node-id',
    'root-node-id',
    'generation',
    'listening',
)
methods = (
    'open',
    'get_config_rom',
    'listen',
    'unlisten'
)
vmethods = (
    'do_bus_update',
    'do_disconnected',
)
signals = (
    'bus-update',
    'disconnected',
)

if not test(target, props, methods, vmethods, signals):
    exit(ENXIO)
