#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

import gi
gi.require_version('Hinawa', '3.0')
from gi.repository import Hinawa

from helper import test_functions

types = {
    Hinawa.FwNodeError: (
        'quark',
    ),
    Hinawa.FwReqError: (
        'quark',
    ),
    Hinawa.FwRespError: (
        'quark',
    ),
    Hinawa.FwFcpError: (
        'quark',
    ),
}

for target_type, functions in types.items():
    if not test_functions(target_type, functions):
        exit(ENXIO)
