#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test

import gi
gi.require_version('Hinawa', '3.0')
from gi.repository import Hinawa

target = Hinawa.SndMotu()
props = ()
methods = (
    'new',
    'open',
    'read_register_dsp_meter',
    'read_command_dsp_meter',
)
vmethods = (
    'do_notified',
    'do_register_dsp_changed',
)
signals = (
    'notified',
    'register-dsp-changed',
)

if not test(target, props, methods, vmethods, signals):
    exit(ENXIO)
