#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('Hinawa', '3.0')
from gi.repository import Hinawa

target_type = Hinawa.SndDice
props = ()
methods = (
    'new',
    'open',
    'transaction',
)
vmethods = (
    'do_notified',
)
signals = (
    'notified',
)

if not test_object(target_type, props, methods, vmethods, signals):
    exit(ENXIO)
