#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test

import gi
gi.require_version('Hinawa', '2.0')
from gi.repository import Hinawa

target = Hinawa.SndDice()
props = ()
methods = (
    'open',
    'transact',
)
signals = (
    'notified',
)

if not test(target, props, methods, signals):
    exit(ENXIO)
