#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('Hinawa', '3.0')
from gi.repository import Hinawa

target_type = Hinawa.SndUnit
props = (
    'type',
    'card',
    'device',
    'streaming',
    'guid',
)
methods = (
    'new',
    'open',
    'get_node',
    'lock',
    'unlock',
)
vmethods = (
    'do_lock_status',
    'do_disconnected',
)
signals = (
    'lock-status',
    'disconnected',
)

if not test_object(target_type, props, methods, vmethods, signals):
    exit(ENXIO)
