#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test

import gi
gi.require_version('Hinawa', '3.0')
from gi.repository import Hinawa

target = Hinawa.SndDg00x()
props = ()
methods = (
    'open',
)
vmethods = (
    'do_message',
)
signals = (
    'message',
)

if not test(target, props, methods, vmethods, signals):
    exit(ENXIO)
