#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_struct

import gi
gi.require_version('Hinawa', '3.0')
from gi.repository import Hinawa

target_type = Hinawa.SndMotuRegisterDspParameter
methods = (
    'new',
    'get_mixer_source_gain',
    'get_mixer_source_pan',
    'get_mixer_source_flag',
    'get_mixer_source_paired_balance',
    'get_mixer_source_paired_width',
    'get_mixer_output_paired_volume',
    'get_mixer_output_paired_flag',
    'get_main_output_paired_volume',
    'get_headphone_output_paired_volume',
    'get_headphone_output_paired_assignment',
    'get_line_input_boost_flag',
    'get_line_input_nominal_level_flag',
    'get_input_gain_and_invert',
    'get_input_flag',
)

if not test_struct(target_type, methods):
    exit(ENXIO)
