#!/usr/bin/env python3

import sys
import errno

from helper import test

import gi
gi.require_version('Hinawa', '2.0')
from gi.repository import Hinawa

target = Hinawa.SndTscm()
props = ()
methods = (
    'open',
    'get_state',
)
signals = (
    'control',
)

if not test(target, props, methods, signals):
    sys.exit(errno.ENXIO)
