#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('Hinawa', '3.0')
from gi.repository import Hinawa

target = Hinawa.SndTscm()
props = ()
methods = (
    'new',
    'open',
    'get_state',
)
vmethods = (
    'do_control',
)
signals = (
    'control',
)

if not test_object(target, props, methods, vmethods, signals):
    exit(ENXIO)
