#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test

import gi
gi.require_version('Hinawa', '2.0')
from gi.repository import Hinawa

target = Hinawa.SndEfw()
props = ()
methods = (
    'new',
    'open',
    'transact',
)
vmethods = ()
signals = ()

if not test(target, props, methods, vmethods, signals):
    exit(ENXIO)
