#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test

import gi
gi.require_version('Hinawa', '2.0')
from gi.repository import Hinawa

target = Hinawa.SndUnit()
props = (
    'type',
    'card',
    'device',
    'streaming',
    'guid',
    'listening',
)
methods = (
    'open',
    'lock',
    'unlock',
    'listen',
    'unlisten',
)
vmethods = (
    'do_lock_status',
)
signals = (
    'lock-status',
)

if not test(target, props, methods, vmethods, signals):
    exit(ENXIO)
