name: Build test

on: [push, pull_request]

jobs:
  build_in_fedora_amd64_on_docker:
    runs-on: ubuntu-latest
    container:
      image: fedora:rawhide
    steps:
    - name: Prepare build environment.
      run: |
        dnf -y upgrade
        dnf -y install @development-tools
        dnf -y install meson gobject-introspection-devel systemd-devel
        dnf -y install gi-docgen python3-gobject
    - name: Checkout repository.
      uses: actions/checkout@v4
    - name: Create gi-docgen.wrap in subproject directory
      run: |
        mkdir subprojects
        cat > subprojects/gi-docgen.wrap << EOF
        [wrap-git]
        directory = gi-docgen
        url = https://gitlab.gnome.org/GNOME/gi-docgen.git
        revision = 2023.1
        depth = 1
        
        [provide]
        program_names = gi-docgen
        EOF
    - name: Initialization for build.
      run: |
        meson --prefix=/tmp. -Ddoc=true -Dwarning_level=3 . build
    - name: Display configuration.
      run: |
        cd build
        meson configure
    - name: Build library.
      run: |
        cd build
        ninja
    - name: Test interfaces exposed by g-i.
      run: |
        cd build
        meson test
    - name: Test install.
      run: |
        cd build
        meson install

  build_in_ubuntu_amd64_on_docker:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
    - name: Prepare build environment.
      run: |
        DEBIAN_FRONTEND=noninteractive apt-get update
        DEBIAN_FRONTEND=noninteractive apt-get -y full-upgrade
        DEBIAN_FRONTEND=noninteractive apt-get install -y git build-essential
        DEBIAN_FRONTEND=noninteractive apt-get install -y meson ninja-build libglib2.0-dev gobject-introspection libgirepository1.0-dev
        DEBIAN_FRONTEND=noninteractive apt-get install -y gi-docgen python3-gi
    - name: Checkout repository.
      uses: actions/checkout@v4
    - name: Create gi-docgen.wrap in subproject directory
      run: |
        mkdir subprojects
        cat > subprojects/gi-docgen.wrap << EOF
        [wrap-git]
        directory = gi-docgen
        url = https://gitlab.gnome.org/GNOME/gi-docgen.git
        revision = 2023.1
        depth = 1
        
        [provide]
        program_names = gi-docgen
        EOF
    - name: Initialization for build.
      run: |
        meson --prefix=/tmp. -Ddoc=true -Dwarning_level=3 . build
    - name: Display configuration.
      run: |
        cd build
        meson configure
    - name: Build library.
      run: |
        cd build
        ninja
    - name: Test interfaces exposed by g-i.
      run: |
        cd build
        meson test
    - name: Test install.
      run: |
        cd build
        meson install
